# Generated by Django 6.0 on 2025-12-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-19 15:40'),
            preserve_default=False,
        ),
    ]
