# Generated by Django 6.0 on 2025-12-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_created_at'),
    ]

    operations = [
    ]
