# Generated by Django 6.0 on 2025-12-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram')], default='kg', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='category',
            table='',
        ),
    ]
